public Class CreatingAccount1 {
 //method implementation here
   ///changes aug17 //////////////
///changes march333 //////////////
 
    public Account createAccount(String name) { //method to create account
        Account acc = new Account();
        acc.Name = name;
        return acc;
        ///////method end here with implementation////// 
             ///changes aug17 //////////////
             
             ///changes September 8th //////////////
            ///Test ////////////// 
            ///sep9 ////////////// 

        
    }
}