///////This class is used creates the account based on the lead status //////

public Class CreatingAccount {
 //method implementation here
    public Account createAccount(String name) { //method to create account
        Account acc = new Account();
        acc.Name = name;
        return acc;
        ///////method end here with implementation////// 
        ///changes on june 15th testt///
    }
}