///////This class is used creates the account based on the lead status //////

public Class CreatingAccount {
 //method implementation here
   ///changes on july 17th //////////////
         ///changes on july 17th //////////////
         ///changes on july 17th //////////////
         ///changes on july 17th //////////////
         ///changes on july 17th //////////////
    public Account createAccount(String name) { //method to create account
        Account acc = new Account();
        acc.Name = name;
        return acc;
        ///////method end here with implementation////// 
             ///changes on july 17th //////////////
         ///changes on july 20th //////////////
         ///changes on july 20th //////////////
         ///changes on july 20th //////////////
         ///changes on july 20th //////////////
        ///changes on july 17th //////////////
         ///changes on july 17th //////////////
         ///changes on july 17th //////////////
         ///changes on july 17th //////////////
         ///changes on july 17th //////////////
        
    }
}